<a href="https://colab.research.google.com/github/ghadaali2010/python-tranning/blob/main/numpy_coding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy
my_list = [1,2,3]
print(type(my_list))
my_array=numpy.array(my_list)
print(type(my_array))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
my_list = [1,2,3]
print(type(my_list))
my_array=np.array(my_list)
print(type(my_array))
from numpy import array
arry1=array(my_list)
print(arry1.shape)
print(arry1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
(3,)
int64


In [ ]:
from numpy import empty
a=empty([3,3])
print(a)

[[2.56526709e-316 1.77863633e-322 0.00000000e+000]
 [0.00000000e+000 2.01589600e-312 1.20098738e-071]
 [1.14195140e-071 4.22009449e-090 2.67956848e-032]]


In [ ]:
from numpy import zeros
z=zeros([3,3])
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
from numpy import ones
o=ones([3,3])
print(o)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np
empty_arr=np.empty([3,1])
zeros_arr=np.zeros([2,2])
ones_arr=np.ones([2,1])
print(empty_arr)
print(zeros_arr)
print(ones_arr)

[[4.9e-324]
 [9.9e-324]
 [1.5e-323]]
[[0. 0.]
 [0. 0.]]
[[1.]
 [1.]]


In [ ]:
import numpy as np
a1=np.array([1,2,3])
a2=np.array([3,6,7])
a3=np.vstack((a1,a2))
a4=np.hstack((a1,a2))
print(a3)
print(a3.shape)
print(a4)
print(a4.shape)

[[1 2 3]
 [3 6 7]]
(2, 3)
[1 2 3 3 6 7]
(6,)


In [ ]:
import numpy as np
a1=np.array([1,2,3])
a2=np.array([4,6,7])
a3=np.vstack((a1,a2))
a4=np.hstack((a1,a2))
print(a3)
print(a3[1,1])
print(a4)
print(a4[0])
print(a4[-4])
print(a4[0:3])

[[1 2 3]
 [4 6 7]]
6
[1 2 3 4 6 7]
1
3
[1 2 3]


In [ ]:
import numpy as np
data=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
train,test = data[:,:-1],data[:,-1]
print(train)
print(test)
split =2
trains,tests = data[:split,:],data[split:,:]
print('the split with 2 is',trains)
print('the split with 2 is',tests)

[[1 2]
 [4 5]
 [7 8]]
[3 6 9]
the split with 2 is [[1 2 3]
 [4 5 6]]
the split with 2 is [[7 8 9]]


In [ ]:
## Write a function that takes data and percent of the train set. Splitsthe data into train and test sets based on the passed percent. Splits both train and test into input and output data.
## Input: data, train_percent
## Outputs: X_train, y_train, X_test, y_test
def train_test_split (data,train_precetage):
  midpoint = train_precentage*(len(data))/100
  train,test=data[:int(midpoint),:], data[int(midpoint):,:]
  x_train,y_train=train[:,:-1],train[:,-1]
  x_test,y_test=test[:,:-1],test[:,-1]
  return x_train,y_train,x_test,y_test


In [ ]:
import numpy as np
my_array=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print('rows:',my_array.shape[0])
print('columns:',my_array.shape[1])


rows: 4
columns: 3


In [ ]:
import numpy as np
data=np.array([11,12,13,4,15,7])
print(data.shape)
one_row=data.reshape((1,data.shape[0]))
print('row data is:',one_row)
print('row shape is :',one_row.shape)
one_colunm=data.reshape((data.shape[0],1))
print('colunm data is:',one_colunm)
print('colunm shape is :',one_colunm.shape)

(6,)
row data is: [[11 12 13  4 15  7]]
row shape is : (1, 6)
colunm data is: [[11]
 [12]
 [13]
 [ 4]
 [15]
 [ 7]]
colunm shape is : (6, 1)


In [ ]:
import numpy as np
data=np.array([[11,12,13],[4,15,7],[23,33,44]])
print(data.shape)
data=data.reshape((data.shape[0],data.shape[1],1))
print(data.shape)
print(data)

(3, 3)
(3, 3, 1)
[[[11]
  [12]
  [13]]

 [[ 4]
  [15]
  [ 7]]

 [[23]
  [33]
  [44]]]


In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([[4,6,7],[4,5,6]])
c_add=a+b
c_sub=a-b
c_sub2=b-a
print(c_add)
print(c_sub)
print(c_sub2)

[[ 5  8 10]
 [ 5  7  9]]
[[-3 -4 -4]
 [-3 -3 -3]]
[[3 4 4]
 [3 3 3]]


In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([[4,6,7],[4,5,6]])
c_add=a+b
print(c_add)

[[ 5  8 10]
 [ 5  7  9]]


In [ ]:
import numpy as np
a=np.array([[1,2,4],[3,7,7],[1,2,4]])
b=np.array([[4,6,7],[4,5,9],[3,4,6]])
c_add=a+b
c_Mul=a*b
c_dot=a.dot(b)
print(c_add)
print(c_Mul)
print(c_dot)


[[ 5  8 11]
 [ 7 12 16]
 [ 4  6 10]]
[[ 4 12 28]
 [12 35 63]
 [ 3  8 24]]
[[ 24  32  49]
 [ 61  81 126]
 [ 24  32  49]]


In [ ]:
import numpy as np
a=np.array([[1,2,4],[3,7,7],[1,2,4]])
lower=np.tril(a) # make lower triangular matrix
print(lower)
upper=np.triu(a) # make upper triangular matrix
print(upper)

[[1 0 0]
 [3 7 0]
 [1 2 4]]
[[1 2 4]
 [0 7 7]
 [0 0 4]]


In [ ]:
import numpy as np
a=np.array([[1,2,4],[3,7,7],[1,2,4]])
d=np.diag(a) # make diagonal matrix
print(d)
I=np.identity(4) # build identity  matrix
print(I)

[1 7 4]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#matrix operation transpose
import numpy as np
a=np.array([[1,2],[3,7],[1,2]]) 
print(a)
A=a.T
print(A)

[[1 2]
 [3 7]
 [1 2]]
[[1 3 1]
 [2 7 2]]


In [ ]:
#matrix operation inverse
import numpy as np
a=np.array([[1,2],[3,7]]) 
print(a)
A=np.linalg.inv(a)
I=a.dot(A)
print(I)

[[1 2]
 [3 7]]
[[ 1.0000000e+00  0.0000000e+00]
 [-4.4408921e-15  1.0000000e+00]]


In [ ]:
#matrix operation trace
import numpy as np
a=np.array([[1,2,4],[3,7,7],[1,3,5]]) 
print(a)
tr=np.trace(a)
print(tr)

[[1 2 4]
 [3 7 7]
 [1 3 5]]
13


In [ ]:
#matrix operation determinant
import numpy as np
a=np.array([[1,2,5],[3,7,7],[2,4,6]]) 
print(a)
A=np.linalg.det(a)
print(A)

[[1 2 5]
 [3 7 7]
 [2 4 6]]
-3.9999999999999973


In [ ]:
#matrix operation rank
import numpy as np
a=np.array([[1,2]]) 
a1=np.array([[1,2,5],[3,7,7],[2,4,6]]) 
print(a)
A=np.linalg.matrix_rank(a)
print(A)
print(a1)
A1=np.linalg.matrix_rank(a1)
print(A1)

[[1 2]]
1
[[1 2 5]
 [3 7 7]
 [2 4 6]]
3


In [ ]:
#SciPy Sparse Matrix
import numpy as np
from scipy.sparse import csr_matrix
A=np.array([[1,0,0,1,0,0],[0,0,2,0,0,1],[0,0,0,2,0,0]])
print(A)
S=csr_matrix(A)
print(S)
B=S.todense()
print(B)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2
[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


In [ ]:
import numpy as np
A=np.array([[1,0,0,1,0,0],[0,0,2,0,0,1],[0,0,0,2,0,0]])
T=np.array([[[1,0,0,1,0,0],[0,0,2,0,0,1],[0,0,0,2,0,0]]])
print(T)
print(T.shape)
print(A.shape)

[[[1 0 0 1 0 0]
  [0 0 2 0 0 1]
  [0 0 0 2 0 0]]]
(1, 3, 6)
(3, 6)


In [ ]:
#Tensor Arithmetic Addition/Multiplication
import numpy as np
T1=np.array([[[1,4,7,1,0,9],[0,10,2,0,40,1],[20,0,50,2,0,3]]])
T2=np.array([[[11,10,20,1,5,8],[0,9,2,0,0,1],[0,3,6,2,10,0]]])
T_add=T1+T2
T_mul=T1*T2
print(T_add)
print(T_mul)

[[[12 14 27  2  5 17]
  [ 0 19  4  0 40  2]
  [20  3 56  4 10  3]]]
[[[ 11  40 140   1   0  72]
  [  0  90   4   0   0   1]
  [  0   0 300   4   0   0]]]


In [ ]:
#Tensor product
import numpy as np
T1=np.array([[[1,4,7],[0,10,2]]])
T2=np.array([[[11,10,20],[0,9,2]]])
T_p=np.tensordot(T1,T2, axes=0)
print(T_p)

[[[[[[ 11  10  20]
     [  0   9   2]]]


   [[[ 44  40  80]
     [  0  36   8]]]


   [[[ 77  70 140]
     [  0  63  14]]]]



  [[[[  0   0   0]
     [  0   0   0]]]


   [[[110 100 200]
     [  0  90  20]]]


   [[[ 22  20  40]
     [  0  18   4]]]]]]


In [ ]:
#Matrix Factorization LU Decomposition
from scipy.linalg import lu
a=np.array([[1,2,5],[3,7,7],[2,4,6]]) 
print(a)
P,L,U=lu(a)
print(P)
print(L)
print(U)
B= P.dot(L).dot(U)
print(B)

[[1 2 5]
 [3 7 7]
 [2 4 6]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
[[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 0.5        1.        ]]
[[ 3.          7.          7.        ]
 [ 0.         -0.66666667  1.33333333]
 [ 0.          0.          2.        ]]
[[1. 2. 5.]
 [3. 7. 7.]
 [2. 4. 6.]]


In [ ]:
#Matrix Factorization QR Decomposition
a=np.array([[1,2,5],[3,7,7],[2,4,6]]) 
print(a)
Q,R=np.linalg.qr(a,'complete')
print(Q)
print(R)
B= Q.dot(R)
print(B)

[[1 2 5]
 [3 7 7]
 [2 4 6]]
[[-2.67261242e-01  3.58568583e-01 -8.94427191e-01]
 [-8.01783726e-01 -5.97614305e-01  1.11022302e-16]
 [-5.34522484e-01  7.17137166e-01  4.47213595e-01]]
[[ -3.74165739  -8.2850985  -10.15592719]
 [  0.          -0.5976143    1.91236577]
 [  0.           0.          -1.78885438]]
[[1. 2. 5.]
 [3. 7. 7.]
 [2. 4. 6.]]


In [3]:
#Matrix Factorization EginDecomposition
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
eign_values,eign_vector=np.linalg.eig(A)
print(eign_values)
print(eign_vector)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [6]:
#Confirm an Eigenvector and Eigenvalue
B=A.dot(eign_vector[:,0])
print(B)
C= eign_vector[:,0]*eign_values[0]
print(C)
Q=eign_vector
R=np.linalg.inv(Q)
L=np.diag(eign_values)
B=Q.dot(L).dot(R)
print(B)

[ -3.73863537  -8.46653421 -13.19443305]
[ -3.73863537  -8.46653421 -13.19443305]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
